# Generated by Django 4.1.6 on 2023-02-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="drink", old_name="name", new_name="github",),
    ]
