# Generated by Django 4.1.6 on 2023-02-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0002_rename_name_drink_github"),
    ]

    operations = [
        migrations.RenameField(model_name="drink", old_name="github", new_name="name",),
    ]
